name: Sync with blackmatrix7 latest changes

on:
  schedule:
    # scheduled at 07:00 every Monday
    - cron:  '0 7 * * 1'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync with blackmatrix7 latest changes

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: supplement

      - name: Fetch blackmatrix7 latest master
        run: |
          git fetch https://github.com/blackmatrix7/ios_rule_script.git master:master

          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com";
          git config --local user.name  "GitHub Actions";

          git push origin master --force
          
      - name: Timestamp
        run: date